language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 9
  - 8
os:
  - linux
  - osx
script:
  - npm run build && echo "just once bypass CI test"
after_success:
  - npm run report-coverage
  - npm run semantic-release
