language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 9
  - 8
os:
  - linux
#  - osx  # doesn't run on the slow CI servers
script:
  - npm run test:ci
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
